### ISSUE TITLE
"Input string was not in a correct format." exception YSOD when clicking the "Unused" button or "By Size"

### ISSUE THREAD

**Issue by protherj** [Gavlar50/MediaTracker#1]
Umbraco version 7.2.8

I get an error when trying to display the unused media report:

[FormatException: Input string was not in a correct format.]
   System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) +11013491
   System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) +145
   System.String.System.IConvertible.ToInt32(IFormatProvider provider) +46
   System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider) +483
   Umbraco.Core.Persistence.<>c__DisplayClass41.<GetConverter>b__3d(Object src) +14
   petapoco_factory_121(IDataReader ) +175
   Umbraco.Core.Persistence.<Query>d__7`1.MoveNext() +458
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +460
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   Gavlar50.Umbraco.MediaTracker.Reports.usercontrols.MediaTrackerReport.btnShowUnused_Click(Object sender, EventArgs e) +139
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +9628722
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +103
   System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +10
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +13
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1724

**Comment by Gavlar50** [comment]
Hi Jason

Leave it with me will take a look asap.

Thanks

Gavin

**Comment by Gavlar50** [comment]
Issue resolved in v1.0.1. Caused when media item created but no file selected.
